services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - box_metrics

networks:
  box_metrics:
    name: box_metrics
    driver: bridge
